
export const PLANS = [
  {
    id: "weekly",
    name: "Weekly",
    price: "USD 19",
    priceKES: "KES 2199",
    usd: 19,
    kes: 2199,
    period: "/week",
    duration: 7,
    features: [
      "15 signals per day",
      "Basic market analysis",
      "Email notifications",
      "Mobile app access",
      "Basic technical indicators",
      "Market news updates",
      "7-day access",
    ],
    benefits: [
      "Perfect for testing our service",
      "No long-term commitment",
      "Full signal access during trial",
      "Email support available",
    ],
    popular: false,
  },
  {
    id: "monthly",
    name: "Monthly",
    price: "USD 49",
    priceKES: "KES 5499",
    usd: 49,
    kes: 5499,
    period: "/month",
    duration: 30,
    features: [
      "35 signals per day",
      "Advanced market analysis",
      "Real-time notifications",
      "Priority support",
      "Advanced technical indicators",
      "AI-powered insights",
      "Risk management tools",
      "Portfolio tracking",
      "30-day access",
    ],
    benefits: [
      "Most popular choice",
      "Best value for active traders",
      "Priority customer support",
      "Advanced AI analysis included",
      "All premium features unlocked",
    ],
    popular: true,
  },
  {
    id: "3months",
    name: "3 Months",
    price: "USD 129",
    priceKES: "KES 14999",
    usd: 129,
    kes: 14999,
    period: "/3 months",
    duration: 90,
    features: [
      "Unlimited signals",
      "Advanced market analysis",
      "Real-time notifications",
      "Priority support",
      "Advanced technical indicators",
      "AI-powered insights",
      "Risk management tools",
      "Portfolio tracking",
      "Extended analysis",
      "90-day access",
      "Save KES 500 vs monthly!",
    ],
    benefits: [
      "Best value for serious traders",
      "Extended commitment = better results",
      "Priority customer support",
      "All premium features included",
      "Save money vs monthly billing",
    ],
    popular: false,
  },
  // {
  //   name: "6 Months",
  //   price: "$149",
  //   period: "/6 months",
  //   features: [
  //     "Unlimited signals",
  //     "AI-powered analysis",
  //     "WhatsApp notifications",
  //     "24/7 support",
  //     "Custom indicators",
  //     "API access",
  //     "Advanced risk management",
  //     "Multi-account support",
  //     "Dedicated support",
  //     "Save $25 vs monthly",
  //   ],
  //   popular: false,
  // },
];