export const PLANS = [
  {
    id: "weekly",
    name: "Weekly",
    price: "USD 27.99",
    priceKES: "KES 3613",
    whopPlanId: "plan_uC7s3rdU2lLGh",
    whopCheckoutUrl: "https://whop.com/checkout/plan_uC7s3rdU2lLGh",
    usd:27.99,
    kes: 3613,
    period: "/week",
    duration: 7,
    features: [
      "Trusted by 10,000+ traders",
      "Access to the Indicator",
      "Access to Video Guides",
      "Regular indicator updates",
      "Full support from our team",
      "Cancel at any time",
    ],
    benefits: [
      "Perfect for testing our service",
      "No long-term commitment",
      "Full signal access during trial",
      "Email support available",
    ],
    popular: false,
  },
  {
    id: "monthly",
    name: "Monthly",
    price: "USD 57.99",
    priceKES: "KES 7486",
    whopPlanId: "plan_ziPdsYhBRtqy7",
    whopCheckoutUrl: "https://whop.com/checkout/plan_ziPdsYhBRtqy7",
    usd: 57.99,
    kes: 7486,
    period: "/month",
    duration: 30,
    features: [
      "Save 37% vs monthly",
      "Trusted by 12,000+ traders",
      "Access to the Indicator",
      "Access to Video Guides",
      "Regular indicator updates",
      "Full support from our team",
      "Cancel at any time",
    ],
    benefits: [
      "Most popular choice",
      "Best value for active traders",
      "Priority customer support",
      "Advanced AI analysis included",
      "All premium features unlocked",
    ],
    popular: true,
  },
  {
    id: "quarterly",
    name: "Quarterly",
    price: "USD 147.99",
    priceKES: "KES 19103",
    whopPlanId: "plan_mT4cUvMgRGKLi",
    whopCheckoutUrl: "https://whop.com/checkout/plan_mT4cUvMgRGKLi",
    usd: 147.99,
    kes: 19103,
    period: "/quarterly",
    duration: 90,
    features: [
      "Only Pay Once",
      "Trusted by 12,000+ traders",
      "Access to the Indicator",
      "Access to Video Guides",
      "Regular indicator updates",
      "Priority support from our team",
      "Cancel at any time",
    ],
    benefits: [
      "Best value for serious traders",
      "Extended commitment = better results",
      "Priority customer support",
      "All premium features included",
      "Save money vs monthly billing",
    ],
    popular: false,
  },
];